apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: alphapulse
data:
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://postgres:postgres@postgres:5432/airflow"
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__FERNET_KEY: "afrRCi0qTwZEvSfVJVGoNbkAWdiSqsXDq-ijdSaIs5g="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: alphapulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      # Init container to create airflow database if needed
      initContainers:
      - name: init-db
        image: infra-airflow:latest
        command: ["airflow", "db", "init"]
        envFrom:
        - configMapRef:
            name: airflow-config
      containers:
      - name: airflow-webserver
        image: infra-airflow:latest
        imagePullPolicy: IfNotPresent
        command: ["airflow", "webserver"]
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: airflow-config
      - name: airflow-scheduler
        image: infra-airflow:latest
        imagePullPolicy: IfNotPresent
        command: ["airflow", "scheduler"]
        envFrom:
        - configMapRef:
            name: airflow-config
        volumeMounts:
        - name: dags-volume
          mountPath: /opt/airflow/dags
      volumes:
      - name: dags-volume
        hostPath:
          path: /Users/liyu/Programing/alphapulse-mlops-platform/airflow/dags
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: airflow
  namespace: alphapulse
spec:
  selector:
    app: airflow
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airflow-ingress
  namespace: alphapulse
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - http:
      paths:
      - path: /airflow
        pathType: Prefix
        backend:
          service:
            name: airflow
            port:
              number: 8080
