apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: alphapulse
data:
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://postgres:postgres@postgres:5432/airflow"
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__FERNET_KEY: "afrRCi0qTwZEvSfVJVGoNbkAWdiSqsXDq-ijdSaIs5g="
  AIRFLOW__WEBSERVER__BASE_URL: "https://alphapulse.luichu.dev/airflow"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: alphapulse
spec:
  replicas: 0
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      imagePullSecrets:
      - name: regcred
      initContainers:
      - name: wait-for-db
        image: postgres:16-alpine
        command: ['sh', '-c', 'until pg_isready -h postgres -p 5432; do echo waiting for database; sleep 2; done;']
      - name: airflow-init
        image: ghcr.io/chuliyu/alphapulse-mlops-platform/airflow:latest
        imagePullPolicy: Always
        command: ["airflow", "db", "migrate"]
        envFrom:
        - configMapRef:
            name: airflow-config
      containers:
      - name: airflow-webserver
        image: ghcr.io/chuliyu/alphapulse-mlops-platform/airflow:latest
        imagePullPolicy: Always
        command: ["airflow", "webserver"]
        env:
        - name: _AIRFLOW_WWW_USER_CREATE
          value: "true"
        - name: _AIRFLOW_WWW_USER_USERNAME
          value: "admin"
        - name: _AIRFLOW_WWW_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: airflow-secrets
              key: password
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "800m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
        envFrom:
        - configMapRef:
            name: airflow-config
      - name: airflow-scheduler
        image: ghcr.io/chuliyu/alphapulse-mlops-platform/airflow:latest
        imagePullPolicy: Always
        command: ["airflow", "scheduler"]
        resources:
          limits:
            cpu: "800m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
        envFrom:
        - configMapRef:
            name: airflow-config
      # Removed emptyDir mount to use DAGs from image
---
apiVersion: v1
kind: Service
metadata:
  name: airflow
  namespace: alphapulse
spec:
  type: ClusterIP # 確保內部存取
  selector:
    app: airflow
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airflow-ingress
  namespace: alphapulse
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.middlewares: alphapulse-admin-auth@kubernetescrd
spec:
  tls:
  - hosts:
    - alphapulse.luichu.dev
  rules:
  - host: alphapulse.luichu.dev
    http:
      paths:
      - path: /airflow
        pathType: Prefix
        backend:
          service:
            name: airflow
            port:
              number: 8080