apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: alphapulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: fastapi
        image: ghcr.io/chuliyu/alphapulse-mlops-platform/fastapi:latest
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres:5432/alphapulse"
        - name: API_VERSION
          value: "v1"
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: alphapulse
spec:
  type: ClusterIP
  selector:
    app: fastapi
  ports:
  - port: 80
    targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress
  namespace: alphapulse
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
spec:
  tls:
  - hosts:
    - alphapulse.luichu.dev
  rules:
  - host: alphapulse.luichu.dev
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: fastapi
            port:
              number: 80