apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: alphapulse
spec:
  replicas: 0
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: fastapi
        image: ghcr.io/chuliyu/alphapulse-mlops-platform/fastapi:latest
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres:5432/alphapulse"
        - name: API_VERSION
          value: "v1"
        - name: ROOT_PATH
          value: "/api"
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        volumeMounts:
        - name: models-volume
          mountPath: /app/models
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: alphapulse
spec:
  type: ClusterIP
  selector:
    app: fastapi
  ports:
  - port: 80
    targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress
  namespace: alphapulse
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.middlewares: alphapulse-strip-api-prefix@kubernetescrd
spec:
  tls:
  - hosts:
    - alphapulse.luichu.dev
  rules:
  - host: alphapulse.luichu.dev
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: fastapi
            port:
              number: 80