apiVersion: apps/v1
kind: Deployment
metadata:
  name: alphapulse-frontend
  namespace: alphapulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alphapulse-frontend
  template:
    metadata:
      labels:
        app: alphapulse-frontend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: frontend
        image: ghcr.io/chuliyu/alphapulse-frontend:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: alphapulse-frontend
  namespace: alphapulse
spec:
  type: LoadBalancer # 修正為 LoadBalancer 以讓外網存取
  selector:
    app: alphapulse-frontend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: alphapulse
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: alphapulse-frontend
            port:
              number: 80