apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: alphapulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "alphapulse"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-init
          mountPath: /docker-entrypoint-initdb.d
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-init
        configMap:
          name: postgres-init-scripts
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: alphapulse
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
