apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainer
  namespace: alphapulse
spec:
  replicas: 0
  selector:
    matchLabels:
      app: trainer
  template:
    metadata:
      labels:
        app: trainer
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: trainer
        image: ghcr.io/chuliyu/alphapulse-mlops-platform/trainer:latest
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres:5432/alphapulse"
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow:5000"
        - name: MODEL_OUTPUT_DIR
          value: "/app/models/saved"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: models-volume
          mountPath: /app/models
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      - name: models-volume
        persistentVolumeClaim:
          claimName: data-pvc # Reuse the same PVC for simplicity, or use subPath
          # subPath: models # If we want to be clean

---
apiVersion: v1
kind: Service
metadata:
  name: trainer
  namespace: alphapulse
spec:
  selector:
    app: trainer
  ports:
  - port: 80
    targetPort: 8080
