apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainer
  namespace: alphapulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trainer
  template:
    metadata:
      labels:
        app: trainer
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: trainer
        image: ghcr.io/chuliyu/alphapulse-mlops-platform/trainer:latest
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: trainer
  namespace: alphapulse
spec:
  selector:
    app: trainer
  ports:
  - port: 80
    targetPort: 8080
